server:
  port: 8082

spring:
  application:
    name: workspace-service
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_workspace
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
