server:
  port: 8083

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_project
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
